branches:
  only:
    - master

env:
  global:
    - RGL_USE_NULL=TRUE

language: r
sudo: required
cache: packages
cran: https://cran.rstudio.com
warnings_are_errors: true

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - covr
  - devtools

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - r-lib/covr
  - r-lib/sessioninfo

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
